# Generated by Django 3.2.6 on 2021-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('pwd', models.CharField(max_length=20, verbose_name='유저 이름')),
                ('name', models.CharField(max_length=20, verbose_name='유저 비밀번호')),
                ('registe_date', models.DateTimeField(auto_now_add=True, verbose_name='계정생성시간')),
            ],
            options={
                'verbose_name': '개인 사용자 유저',
                'verbose_name_plural': '개인 사용자 유저',
                'db_table': 'user',
            },
        ),
    ]
