# Generated by Django 3.2.6 on 2021-08-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registe_date',
            new_name='register_date',
        ),
    ]
