# Generated by Django 3.2.6 on 2021-08-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0002_rename_registe_date_user_register_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pwd',
            new_name='user_pwd',
        ),
    ]
